      IMPLICIT REAL*8 (A-H,O-Z), INTEGER (I-N)
      PARAMETER( NSS=121,NTT=241,NFQ=48)
      PARAMETER( MZZ=60,MRR=60,MGG=1,MO=3,MF=81,MFz=48 )
      COMMON /IONIZ/ STOT,RSTR,TEFF,SSTAR,ROUT,WAS,SUV
      COMMON /MATRIX/A(11),ZM,FTR
      COMMON /MODEL/XXMOD(MZZ,MRR,MGG),
     &     XX1MOD(MZZ,MRR,MGG),EMOD(MZZ,MRR,MGG),
     &     E1MOD(MZZ,MRR,MGG),
     &     RHOMOD(MZZ,MRR,MGG),RHOMOD1(MZZ,MRR,MGG),
     &     SCALZ(MGG),
     &     PPMOD(MZZ,MRR,MGG),YYMOD(MZZ,MRR,MGG),
     &     TTMOD(MZZ,MRR,MGG),EEMOD(MZZ,MRR,MGG),
     &     TR(MZZ,MRR,MGG),TRR(MZZ,MRR,MGG),
     &     TMASS,TMC,ELC,TIME,CLOUDSIZE,rhomax,axis,
     &     DUzone,RRzone,ETzone,ESzone,
     &     IMOD,ISEQ,MZ,MR,MG,IUNIT,NOPT
      COMMON / OPCT / TSUB(MO),ERH(MO),
     $    FEE(MF,MO),GM(MO),AB(MO),FEA(MF,MO),NDST
      PARAMETER( CVEL=2.9979E+10 , BOLTZ=1.380662E-16 , GRAV=6.67E-8 ,
     &           HMAS=1.67356E-24 , ELMAS=9.1095E-28 ,
     &           RBOHR=5.292E-09 , EVOLT=1.6022E-12 ,
     &           EBNDH2=4.476*EVOLT * 0.0 )
      PARAMETER( SOLMAS=1.989E+33 , SOLLUM=3.82E+33 , SOLTEF=5777.0 ,
     &           SOLRAD=6.9626E+10, YEAR=24.*3600.*365.25 ,
     &           ASTRUN=149.6E+11 , PARSEC=3.0857E+18 )
      PARAMETER( PI=3.1415926535 )
      COMMON /POSITION/ IGPOS,IRFR,ZPOS,RPOS,DUPOS,
     &       UPOS,X0,Y0,Z0,
     &       Z00,Z01,Z10,Z11,IZ0,IZ1,IR0,IR1,
     &       IZRF,IZPOS,IRPOS
      COMMON /RESMOD/ STEPS,FACTOR,THETA,PHI,SIZE,MS,MT
      COMMON /WRK/   AA(NFQ,NSS,NTT),FLUX(NFQ),BB(NSS,NTT),
     &               SGRID(NSS),TGRID(NTT),BBOUT(NFQ),
     &               E1(NFQ),E2(NFQ),S1(NFQ),S2(NFQ)
      COMMON / ZOPCT / FQz(MFz),SMz(MZZ,MRR,MGG,MFz),
     &    LzMAP(MFz),NFz
